### PR TITLE
feat: migrated to the alpine image

### PR DESCRIPTION
**Pull request by adubovik**

### CODE REVIEW

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-113.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-113.nightly-test.deltixhub.io
>E2E tests status:

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-113.nightly-test.deltixhub.io
>E2E tests status: success

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-113.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by adubovik** [comment]
Closed as a failed attempt to fix deadlock in the adapter on server startup.

Follow-up investigation points to [issue](https://github.com/googleapis/python-aiplatform/issues/3365) with the vertexai initialization in multi-threading context as a culprit.

**Comment by adubovik** [comment]
Reopened as Ubuntu 23 reached end of life and we need to migrate to either Ubuntu 24 + Python 3.12, or to Alpine.
The latter is better, since the bedrock adapter has already been using this image without issues for a year.

**Comment by adubovik** [comment]
Reopened as Ubuntu 23 reached end of life and we need to migrate to either Ubuntu 24 + Python 3.12, or to Alpine.
The latter is better since Alpine is a slimmer image than Ubuntu and the bedrock adapter has already been using this image without issues for a year.

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-113.nightly-test.deltixhub.io
>E2E tests status: success

**Review by roman-romanov-o — APPROVED** [review]

**Pull request merged**
