### PR TITLE
fix: supported encrypted PDFs with empty password

### PR DESCRIPTION
**Pull request by adubovik**

### CODE REVIEW

**Comment by adubovik** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-98.nightly-test.deltixhub.io
>E2E tests status: failed

**Review by vladisavvv — APPROVED** [review]

**Comment by taa-epam** [comment]
/deploy-review
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/495070)

**Comment by taa-epam** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-98.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by taa-epam** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-98.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by taa-epam** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-98.nightly-test.deltixhub.io
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/495182)

**Comment by taa-epam** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-98.nightly-test.deltixhub.io
>- **Deployment failed**: [failed](https://gitlab.deltixhub.com/Clients/deltix/nightly-test/dial/review/-/pipelines/495217)

**Comment by taa-epam** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-98.nightly-test.deltixhub.io
>E2E tests status: failed

**Comment by taa-epam** [comment]
/deploy-review
>Environment URL: https://chat-ai-dial-adapter-vertexai-pr-98.nightly-test.deltixhub.io
>E2E tests status: success

**Pull request merged**
